### ISSUE TITLE
Cant build

### ISSUE THREAD

**Issue by herun1988** [kaishiqi/I18N-Gettext-Supported#1]
I included this into my project (cocos2d-x), but the project build failed. Can you help?

`Undefined symbols for architecture x86_64:
  "I18N::I18nUtils::getInstance()", referenced from:
      AppDelegate::loadLanguageFile() in AppDelegate.o
      I18N::__(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in AppDelegate.o
  "I18N::I18nUtils::DEFAULT_DOMAIN", referenced from:
      AppDelegate::loadLanguageFile() in AppDelegate.o
  "I18N::I18nUtils::addMO(unsigned char*, std::__1::function<int (int)>, unsigned int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)", referenced from:
      AppDelegate::loadLanguageFile() in AppDelegate.o
  "I18N::I18nUtils::gettext(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)", referenced from:
      I18N::__(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by kaishiqi** [comment]
@herun1988 What systems and ide and version do you use, please tell me.

**Comment by kaishiqi** [comment]
Please confirm whether to open the support of the c++11, because my code using the features of the c++11.
If you are using the xcode, select your project to [Build Settings] tab, find [Apple LLVM x.0 - Language - C++] item, set [C++ Language Dialect] to [GUN++11], and set [C++ Standard Library] to [libc++ (LLVM C++11], then compile. 
Hope I can help you. @herun1988

**Comment by v1993** [comment]
Is it finished?

**Comment by kaishiqi** [comment]
Should be no problem
